# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35865fb2ea0c75ca4d87beb5790d3bc1df3f1c3b4938444084dfa18680835f091c006e3e471dee19d44b91c00919a1480c7d5c869668a17623caee0ad5287622
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  aws_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailgun_secret_password: <%= ENV['MAILGUN_SECRET_PASSWORD'] %>


test:
  secret_key_base: 08365401692a9cd8d07de8100fa9d884c57e4f4073e7414f6a5e50e3a0652e6e5a470f1673b469276d412e19dc966de841d0a50079edc5475f3259879103d196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  aws_access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
  mailgun_secret_password: <%= ENV['MAILGUN_SECRET_PASSWORD'] %>
